// AUTO-GENERATED by scripts/extract-home.mjs — do not edit.
export const pageMeta = {
  title: "OurDreams — Gifts that feel personal",
  description: "OurDreams is a powerful, AI-driven Elementor WordPress theme with 48+ pre-built websites, SEO optimization, and lightning-fast performance. Build with ease!",
  htmlClass: "no-js skrollr skrollr-desktop",
  bodyClass: "home wp-singular page-template-default page page-id-6 wp-embed-responsive wp-theme-ourdreams wp-child-theme-ourdreams-child ourdreams-addons-active elementor-default elementor-kit-3 elementor-page elementor-page-6 ourdreams-theme-ready e--ua-blink e--ua-chrome e--ua-mac e--ua-webkit",
  bodyData: {"data-mobile-nav-style":"classic","data-mobile-nav-trigger-alignment":"left","data-elementor-device-mode":"desktop"} as Record<string, string>,
};
